Second commit
Arpit-Tyagi/social-media-backend pull request #3
Opened 2021-12-28 13:26 UTC by Arpit-Tyagi

Made some change according to the frontend of User Login and Register.

2021-12-28 16:45 UTC, abhirocks550 commented on src/exception.filter.ts
> +  ExceptionFilter,
is this file imported anywherer?

2021-12-28 16:46 UTC, abhirocks550 commented on src/main.ts
>    await app.listen(3030);
Fetch the port number as process.env.PORT_NUMBER || PORT_NUMBER from constant file.

2021-12-28 16:46 UTC, abhirocks550 commented on src/users/users.controller.ts
> +
keep the whitespaces and newlines only wherever required and keep it consistent.

2021-12-28 16:47 UTC, abhirocks550 commented on src/users/users.service.ts
> +            return  new this.userModel(createUserDto).save();
Use try-catch block so that runtime exceptions can be handled.

2021-12-28 16:54 UTC, abhirocks550 commented on src/exception.filter.ts
> +export class AllExceptionsFilter implements ExceptionFilter {
Where does  Binding of Exception is happening?

2021-12-28 16:55 UTC, abhirocks550 commented on src/users/users.service.ts
> +    console.log(createUserDto);
Once testing in done with console. remove the console or if it required at staging add a comment

2021-12-28 16:57 UTC, abhirocks550 requested changes
Previous PR already merged so not able to review other files. Do not merge PR before reviewing.

2022-01-03 08:16 UTC, Arpit-Tyagi commented
Made the required changes.
Can I merge the request??

2023-05-22 10:23 UTC, merged